/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.widit.perpustakaan.view;

/**
 *
 * @author PCL-B00-00
 */
public class FormEntryBuku extends javax.swing.JFrame {

    /**
     * Creates new form FormBuku
     */
    public FormEntryBuku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtThnTerbit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPenulis = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPenerbit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHrgSewa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblValidPenulis = new javax.swing.JLabel();
        txtValidHarga = new javax.swing.JLabel();
        lblValidPenerbit = new javax.swing.JLabel();
        lblValidJudul = new javax.swing.JLabel();
        txtValidThnTerbit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jLabel1.setText("Judul");

        txtJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJudulActionPerformed(evt);
            }
        });
        txtJudul.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJudulKeyReleased(evt);
            }
        });

        jLabel2.setText("Tahun Terbit");

        txtThnTerbit.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtThnTerbitInputMethodTextChanged(evt);
            }
        });
        txtThnTerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThnTerbitActionPerformed(evt);
            }
        });
        txtThnTerbit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtThnTerbitKeyReleased(evt);
            }
        });

        jLabel3.setText("Penulis");

        txtPenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenulisActionPerformed(evt);
            }
        });
        txtPenulis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPenulisKeyReleased(evt);
            }
        });

        jLabel4.setText("Penerbit");

        txtPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenerbitActionPerformed(evt);
            }
        });
        txtPenerbit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPenerbitKeyReleased(evt);
            }
        });

        jLabel5.setText("Harga Sewa Rp.");

        txtHrgSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHrgSewaActionPerformed(evt);
            }
        });
        txtHrgSewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHrgSewaKeyReleased(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblValidPenulis.setForeground(new java.awt.Color(255, 0, 0));

        txtValidHarga.setForeground(new java.awt.Color(255, 51, 0));
        txtValidHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValidHargaKeyReleased(evt);
            }
        });

        lblValidPenerbit.setForeground(new java.awt.Color(255, 0, 0));

        lblValidJudul.setForeground(new java.awt.Color(255, 0, 0));

        txtValidThnTerbit.setForeground(new java.awt.Color(255, 51, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setText("MauLibrary");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(63, 63, 63)
                                .addComponent(txtPenulis))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPenerbit)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtHrgSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addComponent(txtThnTerbit))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValidHarga)
                                    .addComponent(lblValidPenulis)
                                    .addComponent(lblValidPenerbit)
                                    .addComponent(lblValidJudul))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(71, 71, 71)
                                .addComponent(txtJudul))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtValidThnTerbit))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValidJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtThnTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValidThnTerbit)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValidPenulis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValidPenerbit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHrgSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValidHarga)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulActionPerformed

    private void txtThnTerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThnTerbitActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_txtThnTerbitActionPerformed

    private void txtPenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenulisActionPerformed

    private void txtPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenerbitActionPerformed

    private void txtHrgSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHrgSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHrgSewaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String judul = txtJudul.getText().trim();
    String thnTerbit = txtThnTerbit.getText().trim();
    String penulis = txtPenulis.getText().trim();
    String penerbit = txtPenerbit.getText().trim();
    String hrgSewa = txtHrgSewa.getText().trim();
    
    boolean isValid = true;

    if (judul.isEmpty()) {
        lblValidJudul.setText("Judul Harus Diisi.");
        isValid = false;
    } else {
        lblValidJudul.setText("");
    }

    if (thnTerbit.isEmpty()) {
        txtValidThnTerbit.setText("Tahun Terbit Harus Diisi.");
        isValid = false;
    } else {
        txtValidThnTerbit.setText("");
    }

    if (penulis.isEmpty()) {
        lblValidPenulis.setText("Penulis Harus Diisi.");
        isValid = false;
    } else {
        lblValidPenulis.setText("");
    }

    if (penerbit.isEmpty()) {
        lblValidPenerbit.setText("Penerbit Harus Diisi.");
        isValid = false;
    } else {
        lblValidPenerbit.setText("");
    }

    if (hrgSewa.isEmpty()) {
        txtValidHarga.setText("Harga Sewa Harus Diisi.");
        isValid = false;
    } else {
        txtValidHarga.setText("");
    }

    if (isValid) {
        jLabel6.setText("Berhasil Submit");
    } else {
        jLabel6.setText("Silakan Isi Semua Field.");
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtThnTerbitInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtThnTerbitInputMethodTextChanged
    
    }//GEN-LAST:event_txtThnTerbitInputMethodTextChanged

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
    
    }//GEN-LAST:event_formKeyTyped

    private void txtThnTerbitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtThnTerbitKeyReleased
        try {
            long d = Long.parseLong(this.txtThnTerbit.getText());
            if ( d < 0 ){
                throw new NumberFormatException("Tidak Boleh Negatif");
            }

            this.txtValidThnTerbit.setText("");
        } catch (NumberFormatException e) {
            this.txtValidThnTerbit.setText("Inputan Harus Angka dan Tidak Boleh Negatif");
        }
    }//GEN-LAST:event_txtThnTerbitKeyReleased

    private void txtPenulisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPenulisKeyReleased
        String input = this.txtPenulis.getText();
        if (input.matches("[a-zA-Z]+")) { // Hanya huruf
            this.lblValidPenulis.setText("");
        } else {
            this.lblValidPenulis.setText("Inputan Harus Huruf dan Tidak Boleh Angka");
        }
    }//GEN-LAST:event_txtPenulisKeyReleased

    private void txtValidHargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValidHargaKeyReleased

    }//GEN-LAST:event_txtValidHargaKeyReleased

    private void txtHrgSewaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHrgSewaKeyReleased
            try {
            long d = Long.parseLong(this.txtHrgSewa.getText());
            if ( d < 0 ){
                throw new NumberFormatException("Tidak Boleh Negatif");
            }

            txtValidHarga.setText("");
        } catch (NumberFormatException e) {
            txtValidHarga.setText("Inputan Harus Angka dan Tidak Boleh Negatif");
        }
    }//GEN-LAST:event_txtHrgSewaKeyReleased

    private void txtJudulKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJudulKeyReleased
        String input = this.txtJudul.getText();
        if (input.matches("[a-zA-Z0-9\\s-.,]*")) {
            this.lblValidJudul.setText("");
        } else {
            this.lblValidJudul.setText("Inputan Hanya Boleh Huruf dan Angka, Tidak Boleh Karakter Khusus");
    }
    }//GEN-LAST:event_txtJudulKeyReleased

    private void txtPenerbitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPenerbitKeyReleased
        String input = this.txtPenerbit.getText();
        if (input.matches("[a-zA-Z\\s-,.]+")) {
            this.lblValidPenerbit.setText("");
        } else {
            this.lblValidPenerbit.setText("Inputan Harus Huruf dan Tidak Boleh Angka");
        }
    }//GEN-LAST:event_txtPenerbitKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEntryBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEntryBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEntryBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEntryBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEntryBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblValidJudul;
    private javax.swing.JLabel lblValidPenerbit;
    private javax.swing.JLabel lblValidPenulis;
    private javax.swing.JTextField txtHrgSewa;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtPenulis;
    private javax.swing.JTextField txtThnTerbit;
    private javax.swing.JLabel txtValidHarga;
    private javax.swing.JLabel txtValidThnTerbit;
    // End of variables declaration//GEN-END:variables
}
